### ISSUE TITLE
Possibility to buy the whole node

### ISSUE THREAD

**Issue by LosBagros** [pterobilling/pterobilling#119]
Possibility for users to buy whole server node and let them do whatever they want with it

**Comment by MinePlay85** [comment]
Hello, I don't think you can do it. But your idea can be added to PteroBilling.
Best Regards.

**Comment by LosBagros** [comment]
I posted issue on pterodactyl. 🤠

**Comment by MinePlay85** [comment]
No your are on PteroBilling GitHub

**Comment by LosBagros** [comment]
I mean that I also tell them my idea on their github

**Comment by LosBagros** [comment]
Authors of pterodactyl panel are not intrested in this 😕
![Screenshot_20210810_150811_com.github.android.png](https://user-images.githubusercontent.com/45005533/128872456-0aa36df8-b16c-4948-a849-49eb29ed63d4.png)
