### ISSUE TITLE
php artisan p:make:client {email} --admin is failing with error.

### ISSUE THREAD

**Issue by ftsiadimos** [pterobilling/pterobilling#122]
**PteroBilling version**: [e.g. v0.1.0-alpha]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Error logs**
Open the `./storage/logs/laravel.log` file. Copy and paste the content to https://hastebin.pterobilling.org/. Then paste the link of the file here:

**Screenshots**

**Server Information (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Pterodactyl panel: [e.g. v1.3.2]
 - Web server: [e.g. nginx 1.19]
 - Database server: [e.g. MariaDB 10.5]
 - PHP: [e.g. 8.0]
 - Redis server: [e.g. 6.2]

**Additional context**

**Comment by MinePlay85** [comment]
I will close this Issue, re create it, and follow the instruction

**Comment by MinePlay85** [comment]
Or you can copy the issue and write it
