### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by FarmiGames** [pterobilling/pterobilling#148]
[2021-09-06 19:36:52] production.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'pterobilling'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = billing and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'pterobilling'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = billing and table_name = migrations and table_type = 'BASE TABLE') at /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Database/Connection.php:692)
[stacktrace]
#0 /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Database/Connection.php(652): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Database/Connection.php(360): Illuminate\\Database\\Connection->run()
#2 /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(44): Illuminate\\Database\\Connection->select()
#3 /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable()
#4 /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(652): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#5 /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(106): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#6 /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(77): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#7 /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(585): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#8 /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(94): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#9 /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#10 /var/www/pterobilling/vendor/laravel/framework/src/Illuminate/Container/Util.php(40):

**Comment by MinePlay85** [comment]
Re create the Issue with a template and follow it
