### ISSUE TITLE
Error: There are no commands defined in the "p:make" namespace.

### ISSUE THREAD

**Issue by SkyLighted** [pterobilling/pterobilling#156]
**PteroBilling version**: i dont know, newer version. (by "composer create-project pterobilling/pterobilling pterobilling --no-dev --stability=dev")

**Describe the bug**
When i type "php artisan p:make:client {email} --admin" it gives error:
  There are no commands defined in the "p:make" namespace.

  Did you mean one of these?
      make
      optimize
      package

And, if i type "php artisan p:update:settings" it gives error:

  There are no commands defined in the "p:update" namespace.

  Did you mean one of these?
      optimize
      package

And, on site i see "500 | SERVER ERROR"

**To Reproduce**
1. Download pterobilling (I installed by docs steps)
2. Go to /var/www/pterobilling
3. Type this commands OR go to site

**Expected behavior**
I expected working billing.

**Error logs**
Open the `./storage/logs/laravel.log` file. Copy and paste the content to https://hastebin.pterobilling.org/. Then paste the link of the file here: https://hastebin.pterobilling.org/onogupaqux.properties

**Screenshots**
![image](https://user-images.githubusercontent.com/43494452/133986889-e968c7d8-dc75-472d-957a-5930baadd5ce.png)

**Server Information (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Pterodactyl panel: 1.6.1
 - Web server: Apache/2.4.29
 - Database server:  Ver 15.1 Distrib 10.6.4-MariaDB (mysql)
 - PHP: PHP 8.0.10 (cli)
 - Redis server: 6.0.6

**Additional context**
Help pls

**Comment by Bricklou** [comment]
The documentation is ahead compared to the code.
Plus, the project is not stable at all, you can't use it. Please use the demo instead of trying to install it on your machine.
