### ISSUE TITLE
Error creating Admin account

### ISSUE THREAD

**Issue by JHDEZ-HPJ** [pterobilling/pterobilling#253]
When I type this command:
php artisan p:make:client {email} --admin

Is shows me this error:

  There are no commands defined in the "p:make" namespace.

  Did you mean one of these?
      make
      optimize
      package

What can I do?

**Comment by one-juru** [comment]
The documentation is actually ahead of the panel at the moment. This means that you can't create an admin account yet. Please login with the default credentials "admin@example.com" and "password" instead.

**Comment by SkylerFusky** [comment]
That was removed to stop people breaking things before and saying “there are bugs everywhere plz fix!”

we know there are bugs, its not even in its beta yet, so downloading it before its time requires some knowledge.

If you wish to add one yourself you could always try learning SQL, and editing the database yourself, however its not recommended unless you learn first
