### ISSUE TITLE
PayPal Setup

### ISSUE THREAD

**Issue by JHDEZ-HPJ** [pterobilling/pterobilling#254]
When I go to PayPal setting in the panel to activate it, I can't because is empty. If you see the screenshot you will understand better:
![imagen_2022-02-14_134020](https://user-images.githubusercontent.com/90265682/153865906-c18eca39-6105-48b6-b8b1-921146cc8902.png)

**Comment by Bricklou** [comment]
Like @SkylerFusky said here:  https://github.com/pterobilling/pterobilling/issues/253#issuecomment-1039021367
The panel is still in Alpha stage, a lot of things doesn't work or are just not yet implemented.
I would ask you to be patient until the panel is finished. In the meantime, please avoid installing it. :slightly_smiling_face:
