### ISSUE TITLE
Discord server and demo website

### ISSUE THREAD

**Issue by Hiekki4** [pterobilling/pterobilling#37]
Make a Discord support server.

**Comment by Hiekki4** [comment]
And make a demo website of the pterobilling to? I'm so happy :D

**Comment by AkimunCDN** [comment]
There is already official Discord :D
https://discord.gg/Yx99baYU

**Comment by neightyy** [comment]
Invite is expired...

**Comment by neightyy** [comment]
Can i get the new one?

**Comment by MinePlay85** [comment]
Hello,
Here is a new link: [click](https://discord.gg/J4Wn9khg)

**Comment by AlaisterLeung** [comment]
> And make a demo website of the pterobilling to? I'm so happy :D

https://demo.pterobilling.net
