### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by neightyy** [pterobilling/pterobilling#58]
So if panel does only English language, why not add more?
It's great idea, and more people will use that framework.

**Comment by MinePlay85** [comment]
Hello,
Good idea but it's already planed for the release 1.0.
But I can do it but only French language because i learned french.

**Comment by neightyy** [comment]
I can do Polish language, cuz i'm from Poland so, it's good.

**Comment by AlaisterLeung** [comment]
Duplicate of #36
